apiVersion: v1
kind: Pod
metadata:
  name: nginx-interactive-tty-allowed
  labels:
    app: nginx-interactive-tty
spec:
  containers:
  - name: nginx
    image: nginx
    stdin: false
    tty: false
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-privilege-escalation-disallowed
  labels:
    app: nginx-privilege-escalation
spec:
  containers:
  - name: nginx
    image: nginx
    stdin: true
    tty: true