apiVersion: v1
kind: Namespace
metadata:
  name: allowed-namespace
  labels:
    owner: user.agilebank.demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: disallowed-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    owner: user
  name: disallowed-namespace-2
