apiVersion: v1
kind: Pod
metadata:
  name: nginx-apparmor-allowed
  annotations:
    # apparmor.security.beta.kubernetes.io/pod: unconfined # runtime/default
    container.apparmor.security.beta.kubernetes.io/nginx: localhost/custom
  labels:
    app: nginx-apparmor
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-apparmor
  name: nginx-apparmor-allowed-2
spec:
  containers:
  - image: nginx
    name: nginx
    securityContext:
      appArmorProfile:
        localhostProfile: custom
        type: Localhost

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-apparmor
  name: nginx-apparmor-allowed-3
spec:
  containers:
  - image: nginx
    name: nginx
    securityContext:
      appArmorProfile:
        localhostProfile: custom
        type: Localhost
  securityContext:
    appArmorProfile:
      type: Unconfined

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-apparmor
  name: nginx-apparmor-allowed-4
spec:
  containers:
  - image: nginx
    name: nginx
  securityContext:
    appArmorProfile:
      localhostProfile: custom
      type: Localhost

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-apparmor-disallowed
  annotations:
    # apparmor.security.beta.kubernetes.io/pod: unconfined # runtime/default
    container.apparmor.security.beta.kubernetes.io/nginx: unconfined
  labels:
    app: nginx-apparmor
spec:
  ephemeralContainers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx: unconfined
  labels:
    app: nginx-apparmor
  name: nginx-apparmor-disallowed-2
spec:
  containers:
  - image: nginx
    name: nginx

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-apparmor
  name: nginx-apparmor-disallowed-3
spec:
  containers:
  - image: nginx
    name: nginx

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-apparmor
  name: nginx-apparmor-allowed-5
spec:
  containers:
  - image: nginx
    name: nginx
    securityContext:
      appArmorProfile:
        type: Unconfined
  securityContext:
    appArmorProfile:
      localhostProfile: custom
      type: Localhost
