apiVersion: v1
kind: Pod
metadata:
  name: nginx-proc-mount-allowed
  labels:
    app: nginx-proc-mount
spec:
  hostUsers: false
  containers:
  - name: nginx
    image: nginx
    securityContext:
      procMount: Default
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-proc-mount-exempt-image
  labels:
    app: nginx-proc-mount
spec:
  hostUsers: false
  containers:
  - name: nginx
    image: safeimages.com/nginx
    securityContext:
      procMount: Unmasked #Default
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-proc-mount-disallowed
  labels:
    app: nginx-proc-mount
spec:
  hostUsers: false
  containers:
  - name: no-proc-mount-value
    image: nginx
    securityContext:
      procMount: null
  - name: no-proc-mount
    image: nginx
    securityContext: {}
  - name: no-context
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-proc-mount
  name: nginx-proc-mount-disallowed-2
spec:
  ephemeralContainers:
  - image: nginx
    name: nginx
    securityContext:
      procMount: Unmasked
  hostUsers: false

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-proc-mount
  name: nginx-proc-mount-disallowed-3
spec:
  containers:
  - image: nginx
    name: nginx
    securityContext:
      procMount: Unmasked
  hostUsers: false
