apiVersion: v1
kind: Pod
metadata:
  name: nginx-seccomp-allowed
  labels:
    app: nginx-seccomp
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      seccompProfile:
        type: RuntimeDefault
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-seccomp-disallowed
  labels:
    app: nginx-seccomp
spec:
  containers:
  - name: nginx
    image: nginx-exempt
    securityContext:
      seccompProfile:
        type: Unconfined
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-seccomp-allowed-localhost
  labels:
    app: nginx-seccomp
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      seccompProfile:
        type: Localhost
        localhostProfile: profile.json
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-seccomp
  name: nginx-seccomp-disallowed-2
spec:
  ephemeralContainers:
  - image: nginx
    name: nginx

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-seccomp
  name: nginx-seccomp-disallowed-3
spec:
  containers:
  - image: nginx
    name: nginx
    securityContext:
      seccompProfile:
        type: Unconfined

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-seccomp-disallowed2
  labels:
    app: nginx-seccomp
spec:
  securityContext:
    seccompProfile:
      type: Unconfined
  containers:
  - name: nginx
    image: nginx