apiVersion: v1
kind: Pod
metadata:
  name: has-pizza
  labels:
    pizza: is-great
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: does-not-have-pizza
  labels:
    taco: is-great
spec:
  containers:
    - name: nginx
      image: nginx