apiVersion: v1
kind: Pod
metadata:
  name: opa-allowed
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: opa-allowed-2
spec:
  containers:
  - image: ubuntu:20.14
    name: image
    resources:
      limits:
        cpu: 100m
        memory: 30Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-disallowed
spec:
  initContainers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
  ephemeralContainers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-disallowed-2
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
  initContainers:
  - image: nginx
    name: nginxinit
    resources:
      limits:
        cpu: 100m
        memory: 30Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-disallowed-3
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        cpu: 100m
        memory: 30Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: image-disallowed
spec:
  containers:
    - name: image-1-malicious-basic-image-disallow
      image: ubuntumalicious
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
    - name: image-2-basic-image-allow
      image: ubuntu:20.14
      resources:
        limits:
          cpu: "200m"
          memory: "50Mi"
    - name: image-3-malicious-image-with-registry-disallow
      image: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/postgresmalicious
      resources:
        limits:
          cpu: "50m"
          memory: "10Mi"
    - name: image-4-image-with-registry-allow
      image: 123456789123.dkr.ecr.eu-west-1.amazonaws.com/postgres
      resources:
        limits:
          cpu: "50m"
          memory: "10Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-disallowed-4
spec:
  containers:
  - args:
    - run
    - --server
    - --addr=localhost:8080
    image: openpolicyagent/opa:0.9.2
    name: opa
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
  initContainers:
  - image: nginx
    name: nginxinit
    resources:
      limits:
        cpu: 100m
        memory: 30Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: registry-repository-disallowed
spec:
  containers:
    - name: image-1-malicious-registry-disallow
      image: myregistry.azurecr.io.malicious.com/malicious-image
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
    - name: image-2-registry-allow
      image: myregistry.azurecr.io/nginx
      resources:
        limits:
          cpu: "200m"
          memory: "50Mi"
    - name: image-3-malicious-image-with-registry-disallow
      image: mydockerhubmalicious/python
      resources:
        limits:
          cpu: "50m"
          memory: "10Mi"
    - name: image-4-image-with-registry-allow
      image: mydockerhub/python
      resources:
        limits:
          cpu: "50m"
          memory: "10Mi"