apiVersion: v1
kind: Pod
metadata:
  name: kustomize-allowed
spec:
  containers:
    - name: kustomize
      image: registry.k8s.io/kustomize/kustomize:v3.8.9
---
apiVersion: v1
kind: Pod
metadata:
  name: kustomize-disallowed
spec:
  initContainers:
  - name: kustomize
    image:  k8s.gcr.io/kustomize/kustomize:v3.8.9
  containers:
    - name: kustomize
      image: k8s.gcr.io/kustomize/kustomize:v3.8.9
  ephemeralContainers:
    - name: kustomize
      image: k8s.gcr.io/kustomize/kustomize:v3.8.9
---
apiVersion: v1
kind: Pod
metadata:
  name: kustomize-disallowed-2
spec:
  containers:
  - image: k8s.gcr.io/kustomize/kustomize:v3.8.9
    name: kustomize
  initContainers:
  - image: k8s.gcr.io/kustomize/kustomize:v3.8.9
    name: kustomizeinit

---
apiVersion: v1
kind: Pod
metadata:
  name: kustomize-disallowed-3
spec:
  containers:
  - image: k8s.gcr.io/kustomize/kustomize:v3.8.9
    name: kustomize

---
apiVersion: v1
kind: Pod
metadata:
  name: kustomize-disallowed-4
spec:
  containers:
  - image: registry.k8s.io/kustomize/kustomize:v3.8.9
    name: kustomize
  initContainers:
  - image: k8s.gcr.io/kustomize/kustomize:v3.8.9
    name: kustomizeinit
